server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huangzhenshi/config-test/     # 配置git仓库的地址
          search-paths: config-repo,config-test                            # git仓库地址下的相对地址，可以配置多个，用,分割。
eureka:
  client:
    serviceUrl:
      defaultZone: http://huangzs:123456@localhost:8762/eureka/
